#!/bin/sh

# script/test: Run test suite for application.

RELEASEIT_CONFIG="../dotfiles-org/.release-it.json"

cd "$(dirname "$0")/.." || exit

if [ -f "${RELEASEIT_CONFIG}" ]; then
  echo "==> Running Release-It..."
  release-it --config="${PRECOMMIT_CONFIG}"
fi
