#!/bin/sh

# script/setup: Set up application for the first time after cloning

set -o errexit; set -o nounset

PRECOMMIT_CONFIG="../dotfiles-org/.pre-commit-config.yaml"

cd "$(dirname "$0")/.."

if [ -f "${PRECOMMIT_CONFIG}" ]; then
  echo "==> Removing current pre-commit installation..."
  pre-commit uninstall

  echo "==> Installing pre-commit dependencies..."
  pre-commit install
fi
