#!/bin/sh

# script/test: Run test suite for application.

PRECOMMIT_CONFIG="../dotfiles-org/.pre-commit-config.yaml"

cd "$(dirname "$0")/.." || exit

if [ -f "${PRECOMMIT_CONFIG}" ]; then
  echo "==> Running pre-commit checks..."
  pre-commit run --config="${PRECOMMIT_CONFIG}" --files ./*.*
fi

mocha \
    --bail \
    --check-leaks \
    --inline-diffs \
    --exit \
    --no-timeouts
