---

name: Deployment

on:
  release:
    types: [published]

env:
  NODE_VERSION: 12

jobs:
  publish-to-gpr:
    runs-on: ubuntu-latest
    name: publish-to-gpr

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://npm.pkg.github.com'

      - name: Publish to GitHub Package Registry
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
